// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
  grant_type?: string | null
  username: string
  password: string
  scope?: string
  client_id?: string | null
  client_secret?: string | null
}

export type HTTPValidationError = {
  detail?: Array<ValidationError>
}

export type ItemCreate = {
  title: string
  description?: string | null
}

export type ItemPublic = {
  title: string
  description?: string | null
  id: string
  owner_id: string
}

export type ItemsPublic = {
  data: Array<ItemPublic>
  count: number
}

export type ItemUpdate = {
  title?: string | null
  description?: string | null
}

export type Message = {
  message: string
}

export type NewPassword = {
  token: string
  new_password: string
}

export type PrivateUserCreate = {
  email: string
  password: string
  full_name: string
  is_verified?: boolean
}

export type ProductCreate = {
  name: string
  estimated_selling_price: number | string
  purchase_id: string
}

export type ProductPublic = {
  name: string
  estimated_selling_price: string
  id: string
  purchase_id: string
}

export type ProductsPublic = {
  data: Array<ProductPublic>
  count: number
}

export type ProductUpdate = {
  name?: string | null
  estimated_selling_price?: number | string | null
}

export type PurchaseCreate = {
  date: string
  price: number | string
  name?: string | null
}

export type PurchasePublic = {
  date: string
  price: string
  name?: string | null
  id: string
  owner_id: string
  products: Array<ProductPublic>
}

export type PurchasesPublic = {
  data: Array<PurchasePublic>
  count: number
}

export type PurchaseUpdate = {
  date?: string | null
  price?: number | string | null
  name?: string | null
}

export type SaleCreate = {
  date: string
  total_price: number | string
}

export type SalePublic = {
  date: string
  total_price: string
  id: string
  owner_id: string
  products?: Array<ProductPublic> | null
}

export type SalesPublic = {
  data: Array<SalePublic>
  count: number
}

export type SaleUpdate = {
  date?: string | null
  total_price?: number | string | null
}

export type Token = {
  access_token: string
  token_type?: string
}

export type UpdatePassword = {
  current_password: string
  new_password: string
}

export type UserCreate = {
  email: string
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  password: string
}

export type UserPublic = {
  email: string
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  id: string
}

export type UserRegister = {
  email: string
  password: string
  full_name?: string | null
}

export type UsersPublic = {
  data: Array<UserPublic>
  count: number
}

export type UserUpdate = {
  email?: string | null
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  password?: string | null
}

export type UserUpdateMe = {
  full_name?: string | null
  email?: string | null
}

export type ValidationError = {
  loc: Array<string | number>
  msg: string
  type: string
}

export type ItemsReadItemsData = {
  limit?: number
  skip?: number
}

export type ItemsReadItemsResponse = ItemsPublic

export type ItemsCreateItemData = {
  requestBody: ItemCreate
}

export type ItemsCreateItemResponse = ItemPublic

export type ItemsReadItemData = {
  id: string
}

export type ItemsReadItemResponse = ItemPublic

export type ItemsUpdateItemData = {
  id: string
  requestBody: ItemUpdate
}

export type ItemsUpdateItemResponse = ItemPublic

export type ItemsDeleteItemData = {
  id: string
}

export type ItemsDeleteItemResponse = Message

export type LoginLoginAccessTokenData = {
  formData: Body_login_login_access_token
}

export type LoginLoginAccessTokenResponse = Token

export type LoginTestTokenResponse = UserPublic

export type LoginRecoverPasswordData = {
  email: string
}

export type LoginRecoverPasswordResponse = Message

export type LoginResetPasswordData = {
  requestBody: NewPassword
}

export type LoginResetPasswordResponse = Message

export type LoginRecoverPasswordHtmlContentData = {
  email: string
}

export type LoginRecoverPasswordHtmlContentResponse = string

export type PrivateCreateUserData = {
  requestBody: PrivateUserCreate
}

export type PrivateCreateUserResponse = UserPublic

export type ProductsReadProductsData = {
  limit?: number
  skip?: number
}

export type ProductsReadProductsResponse = ProductsPublic

export type ProductsCreateProductData = {
  requestBody: ProductCreate
}

export type ProductsCreateProductResponse = ProductPublic

export type ProductsReadProductData = {
  id: string
}

export type ProductsReadProductResponse = ProductPublic

export type ProductsUpdateProductData = {
  id: string
  requestBody: ProductUpdate
}

export type ProductsUpdateProductResponse = ProductPublic

export type ProductsDeleteProductData = {
  id: string
}

export type ProductsDeleteProductResponse = Message

export type PurchasesReadPurchasesData = {
  limit?: number
  skip?: number
}

export type PurchasesReadPurchasesResponse = PurchasesPublic

export type PurchasesCreatePurchaseData = {
  requestBody: PurchaseCreate
}

export type PurchasesCreatePurchaseResponse = PurchasePublic

export type PurchasesReadPurchaseData = {
  id: string
}

export type PurchasesReadPurchaseResponse = PurchasePublic

export type PurchasesUpdatePurchaseData = {
  id: string
  requestBody: PurchaseUpdate
}

export type PurchasesUpdatePurchaseResponse = PurchasePublic

export type PurchasesDeletePurchaseData = {
  id: string
}

export type PurchasesDeletePurchaseResponse = Message

export type SalesReadSalesData = {
  limit?: number
  skip?: number
}

export type SalesReadSalesResponse = SalesPublic

export type SalesCreateSaleData = {
  requestBody: SaleCreate
}

export type SalesCreateSaleResponse = SalePublic

export type SalesReadSaleData = {
  id: string
}

export type SalesReadSaleResponse = SalePublic

export type SalesUpdateSaleData = {
  id: string
  requestBody: SaleUpdate
}

export type SalesUpdateSaleResponse = SalePublic

export type SalesDeleteSaleData = {
  id: string
}

export type SalesDeleteSaleResponse = Message

export type UsersReadUsersData = {
  limit?: number
  skip?: number
}

export type UsersReadUsersResponse = UsersPublic

export type UsersCreateUserData = {
  requestBody: UserCreate
}

export type UsersCreateUserResponse = UserPublic

export type UsersReadUserMeResponse = UserPublic

export type UsersDeleteUserMeResponse = Message

export type UsersUpdateUserMeData = {
  requestBody: UserUpdateMe
}

export type UsersUpdateUserMeResponse = UserPublic

export type UsersUpdatePasswordMeData = {
  requestBody: UpdatePassword
}

export type UsersUpdatePasswordMeResponse = Message

export type UsersRegisterUserData = {
  requestBody: UserRegister
}

export type UsersRegisterUserResponse = UserPublic

export type UsersReadUserByIdData = {
  userId: string
}

export type UsersReadUserByIdResponse = UserPublic

export type UsersUpdateUserData = {
  requestBody: UserUpdate
  userId: string
}

export type UsersUpdateUserResponse = UserPublic

export type UsersDeleteUserData = {
  userId: string
}

export type UsersDeleteUserResponse = Message

export type UtilsTestEmailData = {
  emailTo: string
}

export type UtilsTestEmailResponse = Message

export type UtilsHealthCheckResponse = boolean
