"""Add Product, Purchase and Sale

Revision ID: 88bd300fdd17
Revises: 1a31ce608336
Create Date: 2025-03-27 20:41:00.313968

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '88bd300fdd17'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sale',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_price', sa.Numeric(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('estimated_selling_price', sa.Numeric(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('purchase_id', sa.Uuid(), nullable=False),
    sa.Column('sale_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchase.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sale_id'], ['sale.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    op.drop_table('sale')
    op.drop_table('purchase')
    # ### end Alembic commands ###
