"""Make purchase_id nullable

Revision ID: aaa9c65c1da5
Revises: 1e08ed636ba2
Create Date: 2025-04-18 21:06:53.380509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaa9c65c1da5'
down_revision = '1e08ed636ba2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'purchase_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('product_purchase_id_fkey', 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'purchase', ['purchase_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key('product_purchase_id_fkey', 'product', 'purchase', ['purchase_id'], ['id'], ondelete='CASCADE')
    op.alter_column('product', 'purchase_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
