"""Add owner_id to Product models

Revision ID: b21c50f691a4
Revises: aaa9c65c1da5
Create Date: 2025-04-22 14:58:45.583952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b21c50f691a4'
down_revision = 'aaa9c65c1da5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('owner_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'product', 'user', ['owner_id'], ['id'], ondelete='CASCADE')

    # Assign products to the first existing superuser
    op.execute('''
        UPDATE product
        SET owner_id = (
            SELECT id FROM "user"
            WHERE is_superuser = TRUE
            LIMIT 1
        )
    ''')

    # Make the column non-nullable
    op.alter_column('product', 'owner_id', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'owner_id')
    # ### end Alembic commands ###
