/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as ResetPasswordImport } from './routes/reset-password'
import { Route as RecoverPasswordImport } from './routes/recover-password'
import { Route as LoginImport } from './routes/login'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutSettingsImport } from './routes/_layout/settings'
import { Route as LayoutItemsImport } from './routes/_layout/items'
import { Route as LayoutAdminImport } from './routes/_layout/admin'
import { Route as LayoutSalesIndexImport } from './routes/_layout/sales/index'
import { Route as LayoutPurchasesIndexImport } from './routes/_layout/purchases/index'
import { Route as LayoutSalesSaleIdImport } from './routes/_layout/sales/$saleId'
import { Route as LayoutPurchasesPurchaseIdImport } from './routes/_layout/purchases/$purchaseId'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const ResetPasswordRoute = ResetPasswordImport.update({
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const RecoverPasswordRoute = RecoverPasswordImport.update({
  path: '/recover-password',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSettingsRoute = LayoutSettingsImport.update({
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutItemsRoute = LayoutItemsImport.update({
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAdminRoute = LayoutAdminImport.update({
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSalesIndexRoute = LayoutSalesIndexImport.update({
  path: '/sales/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutPurchasesIndexRoute = LayoutPurchasesIndexImport.update({
  path: '/purchases/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSalesSaleIdRoute = LayoutSalesSaleIdImport.update({
  path: '/sales/$saleId',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutPurchasesPurchaseIdRoute = LayoutPurchasesPurchaseIdImport.update({
  path: '/purchases/$purchaseId',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/recover-password': {
      preLoaderRoute: typeof RecoverPasswordImport
      parentRoute: typeof rootRoute
    }
    '/reset-password': {
      preLoaderRoute: typeof ResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/_layout/admin': {
      preLoaderRoute: typeof LayoutAdminImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/items': {
      preLoaderRoute: typeof LayoutItemsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/settings': {
      preLoaderRoute: typeof LayoutSettingsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/purchases/$purchaseId': {
      preLoaderRoute: typeof LayoutPurchasesPurchaseIdImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/sales/$saleId': {
      preLoaderRoute: typeof LayoutSalesSaleIdImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/purchases/': {
      preLoaderRoute: typeof LayoutPurchasesIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/sales/': {
      preLoaderRoute: typeof LayoutSalesIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutRoute.addChildren([
    LayoutAdminRoute,
    LayoutItemsRoute,
    LayoutSettingsRoute,
    LayoutIndexRoute,
    LayoutPurchasesPurchaseIdRoute,
    LayoutSalesSaleIdRoute,
    LayoutPurchasesIndexRoute,
    LayoutSalesIndexRoute,
  ]),
  LoginRoute,
  RecoverPasswordRoute,
  ResetPasswordRoute,
  SignupRoute,
])

/* prettier-ignore-end */
